// Generated by a protocol buffer plugin. DO NOT EDIT!
// See https://github.com/jakebman/proto-java/ for the source to this probuf-plugin
// source: ${REPLACEME_PROTO_FILE_NAME}${REPLACEME_PROTO_FILE_NAME}

package ${REPLACEME_PROTO_JAVA_PACKAGE};

public interface ${REPLACEME_PROTO_JAVA_CLASS}_Mixin extends
        ${REPLACEME_PROTO_JAVA_CLASS_OR_BUILDER_FULL_PACKAGE} {
    // @@protoc_insertion_point(${REPLACEME_PROTO_INSERTION_POINT_COORDINATES})
}
