
package com.boeckerman.jake.protobuf;

import com.google.protobuf.DescriptorProtos;
import com.google.protobuf.GeneratedMessage;

/**
 * A marker interface to identify when this class was generated by.
 * Hopefully, even if no other trace exists, you can start your diagnostics with this
 */
public interface Touched {
    GeneratedMessage.GeneratedExtension<DescriptorProtos.FieldOptions, Extensions.JavaFieldExtension> by = Extensions.javaHelper;
    String MESSAGE = "added by Jake Boeckerman's protoc plugin, for traceabiltiy purposes";
}
